### ISSUE TITLE
Update icon names according to official Sketch template names

### ISSUE THREAD

**Issue by artemnovichkov** [artemnovichkov/sasha#13]
![screen shot 2018-09-20 at 10 21 36](https://user-images.githubusercontent.com/5051597/45795757-14e30d80-bcbf-11e8-8d77-03b9504de42d.png)

**Comment by eerie444** [comment]
Hey @artemnovichkov, I can work on this. Are the Apple Watch icons the only ones whose names need to change, or do all Apple icons?

**Comment by artemnovichkov** [comment]
Hi, @erikstrottmann! The issue related to Apple Watch icons only.
